Repository projectdiscovery/dnsx, pull requests merged in 2020-12, with the labels that each got.

#8 lowercase output
  go.mod
  go.sum
  internal/runner/runner.go
Labels: Status: Review Needed, Type: Bug

#14 [Bugfix] Reduced number of default threads
  internal/runner/options.go
Labels: Type: Bug

#16 go 1.15
  .github/workflows/build.yaml
  .github/workflows/release.yml
  Dockerfile
  README.md
  go.mod
  go.sum
Labels: Status: Accepted
